### ISSUE TITLE
Unable to run process-samples.sh Split on demo data or my own

### ISSUE THREAD

**Issue by hmgill** [Novartis/EQP-cluster#5]
Hello, 

I installed the EQP-cluster as per the instructions & it seems to have installed without any problems (creation of Bowtie2 indices completed). 

When I attempt to use Split though (./process-samples.sh split), I get the message below:

Samples: sample1 sample2
Sample sample1
Split job SP-sample1-209 is still in job queue ... skipping sample sample1
Sample sample2
Split job SP-sample2-209 is still in job queue ... skipping sample sample2

This also happens when I try the -noqsub 1 option. I also tried using my own data but the same message appears. 
There is also no data in the log and fastq files subdirectories in the sample 1, 2 directories. 

Wasn't able to find anything online about this. 
I was wondering what I should try?
Please let me know if there is something I can clarify

Thanks in advance!
Hunter

**Comment by sven0schuierer** [comment]
Hi Hunter,

As you have probably seen this repository has not been maintained for a couple of years, mainly due to lack of interest and I am also working on other projects now. I am sorry.

I would suggest to use the rail pipeline of recount2 (https://github.com/leekgroup/recount-contributions) which also delivers gene, exon, and junction counts and which is still maintained.

Best regards,

Sven
